# core/film_interpolator.py
"""
FILM Frame Interpolator for FUK Pipeline

Google's FILM (Frame Interpolation for Large Motion) via the PyTorch port.
Replaces RIFE with in-process PyTorch inference — no external binaries.

Model: dajes/frame-interpolation-pytorch (Apache 2.0)
Paper: Reda et al., FILM: Frame Interpolation for Large Motion, ECCV 2022

Precision, and why it is not what it looks like
    The model itself takes arbitrary float tensors — interpolate_pair accepts
    whatever you hand it. Everything limiting this to 8-bit is in *our* wrapper,
    not the model and not a vendored engine:

      _load_frame   reads 8- or 16-bit via IMREAD_UNCHANGED, scales by dtype
      _save_frame   clamps to [0,1] and writes 8- or 16-bit PNG
      precision     float32 by default, on CPU and CUDA alike

    Clamping happens only at the PNG writer, so interpolate_frames itself
    carries whatever range the model produced. Feeding it linear-light float is
    therefore a matter of skipping the PNG stage entirely — no patch against
    anyone else's repo, unlike seedvr2_backend where the 8-bit round trip is
    baked into a vendored engine. The remaining question is behavioural: FILM
    was trained on display-referred images, so linear light is out of
    distribution, and that is untested here.

Why this is not in the latent -> EXR path
    Bit depth is the smaller problem. Interpolation *changes the frame count*,
    and in a VFX sequence the beauty EXR has to stay in lockstep with its AOVs.

    Cryptomattes cannot be interpolated at all — they are object ID maps, and a
    blend of two IDs is not a third object. Depth blends across occlusion edges
    and normals need renormalising, so neither survives naive interpolation
    either.

    The fix is ordering, not precision: interpolate the beauty first, then
    generate depth/normals/crypto from the interpolated sequence, so every layer
    derives from the same frames and crypto is regenerated by SAM2 on real
    images rather than blended. Interpolating after AOV generation desynchronises
    the sequence and silently corrupts the mattes.

    There is no latent-space shortcut here either, for a different reason than
    SeedVR2: Wan's VAE is 4x temporally compressed, so latent frames are not
    video frames and interpolating them interpolates groups of four.

Usage:
    interpolator = FILMInterpolator()
    result = interpolator.interpolate_video(
        input_path, output_path,
        source_fps=16, target_fps=24,
    )
"""

import sys
import os
import subprocess
import tempfile
import time
import json
import math
from pathlib import Path
from typing import Optional, Dict, Any, Callable, List, Tuple

import cv2
import numpy as np
import torch
from PIL import Image

# ============================================================================
# Constants
# ============================================================================

# TorchScript model from: https://github.com/dajes/frame-interpolation-pytorch/releases
FILM_MODEL_URL = "https://github.com/dajes/frame-interpolation-pytorch/releases/download/v1.0.2/film_net_fp32.pt"
FILM_MODEL_FILENAME = "film_net_fp32.pt"

# Default cache location for the model
DEFAULT_MODEL_DIR = Path.home() / "ai" / "models" / "film"


# ============================================================================
# FILM Interpolator
# ============================================================================

class FILMInterpolator:
    """
    FILM frame interpolation using native PyTorch.
    
    Key advantages over RIFE-ncnn:
    - Float32 tensors throughout (no uint8 quantization)
    - Native PyTorch (no external binary dependency)
    - Better quality for large motion (FILM's core innovation)
    - Recursive binary interpolation for optimal quality at any multiplier
    
    The model operates on normalized [0, 1] float tensors with shape (B, 3, H, W).
    Frames stay in float32 until final output.
    """
    
    def __init__(
        self,
        models_dir: Optional[Path] = None,
        device: Optional[str] = None,
        precision: Optional[torch.dtype] = None,
    ):
        self.models_dir = models_dir or DEFAULT_MODEL_DIR
        self.models_dir.mkdir(parents=True, exist_ok=True)

        self.device = torch.device(device or ("cuda" if torch.cuda.is_available() else "cpu"))
        # float32 by default, including on CUDA. This used to be fp16 on GPU for
        # speed, which is fine for an 8-bit deliverable and not fine for anything
        # feeding EXR: fp16 carries ~3 decimal digits, so it quantises visibly
        # once the result is written to a float target. FILM is a small model and
        # the frame stack is held on CPU, so fp32 costs little here.
        self.precision = precision or torch.float32

        self.model = None
        self._model_path = self.models_dir / FILM_MODEL_FILENAME
        
        print(f"[FILM] Initialized")
        print(f"[FILM] Device: {self.device}, Precision: {self.precision}")
        print(f"[FILM] Model path: {self._model_path}")
        print(f"[FILM] Model available: {self._model_path.exists()}")
    
    # ========================================================================
    # Model Management
    # ========================================================================
    
    def _ensure_model(self):
        """Load model if not already loaded, download if needed."""
        if self.model is not None:
            return
        
        if not self._model_path.exists():
            self._download_model()
        
        print(f"[FILM] Loading TorchScript model from {self._model_path}...")
        start = time.time()
        self.model = torch.jit.load(str(self._model_path), map_location="cpu")
        self.model.eval().to(device=self.device, dtype=self.precision)
        print(f"[FILM] Model loaded in {time.time() - start:.1f}s")
    
    def _download_model(self):
        """Download FILM TorchScript model from GitHub releases."""
        print(f"[FILM] Model not found at {self._model_path}")
        print(f"[FILM] Downloading from {FILM_MODEL_URL}...")
        
        self.models_dir.mkdir(parents=True, exist_ok=True)
        
        try:
            import urllib.request
            temp_path = self._model_path.with_suffix(".tmp")
            urllib.request.urlretrieve(FILM_MODEL_URL, str(temp_path))
            temp_path.rename(self._model_path)
            print(f"[FILM] Downloaded to {self._model_path}")
        except Exception as e:
            print(f"[FILM] Auto-download failed: {e}")
            print(f"[FILM] Please download manually:")
            print(f"[FILM]   wget {FILM_MODEL_URL} -O {self._model_path}")
            raise RuntimeError(
                f"FILM model not found. Download from:\n"
                f"  {FILM_MODEL_URL}\n"
                f"Place at: {self._model_path}"
            )
    
    def cleanup(self):
        """Unload model and free VRAM."""
        if self.model is not None:
            del self.model
            self.model = None
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
            print("[FILM] Model unloaded, VRAM freed")
    
    # ========================================================================
    # Frame I/O — float32 native
    # ========================================================================
    
    def _load_frame(self, path: Path) -> torch.Tensor:
        """
        Load an image as a float32 tensor [1, 3, H, W], normalised to [0, 1].

        IMREAD_UNCHANGED rather than IMREAD_COLOR: the latter silently converts
        16-bit sources down to 8-bit, which defeats the point of feeding this a
        high-precision sequence. The divisor follows the source dtype — dividing
        a uint16 image by 255 (as the old path would have) yields values up to
        257, not a range this model has ever seen.

        Alpha is dropped: the model is 3-channel. Interpolating it would need a
        separate pass, which nothing asks for yet.
        """
        img = cv2.imread(str(path), cv2.IMREAD_UNCHANGED)
        if img is None:
            raise ValueError(f"Could not load frame: {path}")

        if img.ndim == 2:                       # greyscale -> 3 channels
            img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
        elif img.shape[2] == 4:
            img = cv2.cvtColor(img, cv2.COLOR_BGRA2RGB)
        else:
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        scale = 65535.0 if img.dtype == np.uint16 else 255.0
        tensor = torch.from_numpy(np.ascontiguousarray(img)).permute(2, 0, 1)
        return (tensor.unsqueeze(0).float() / scale).to(dtype=torch.float32)

    def _save_frame(self, tensor: torch.Tensor, path: Path, bit_depth: int = 8):
        """
        Save a [1, 3, H, W] float tensor as an 8- or 16-bit PNG.

        Clamping happens here and only here — the tensor pipeline itself carries
        whatever range the model produced, so a caller writing to EXR never has
        its highlights cut off on the way past.
        """
        img = tensor.squeeze(0).clamp(0, 1).float().cpu()
        if bit_depth == 16:
            arr = (img * 65535.0).round().permute(1, 2, 0).numpy().astype(np.uint16)
        else:
            arr = (img * 255.0).round().permute(1, 2, 0).numpy().astype(np.uint8)
        cv2.imwrite(str(path), cv2.cvtColor(arr, cv2.COLOR_RGB2BGR))
    
    # ========================================================================
    # Core Interpolation
    # ========================================================================
    
    @torch.no_grad()
    def interpolate_pair(
        self, frame1: torch.Tensor, frame2: torch.Tensor, dt: float = 0.5
    ) -> torch.Tensor:
        """
        Interpolate a single frame between two input frames.
        
        Args:
            frame1: [1, 3, H, W] tensor in [0, 1]
            frame2: [1, 3, H, W] tensor in [0, 1]  
            dt: Time position between frames (0.0 = frame1, 1.0 = frame2)
        
        Returns:
            Interpolated frame [1, 3, H, W] in [0, 1]
        """
        self._ensure_model()
        
        # FILM needs height and width divisible by 32
        _, _, h, w = frame1.shape
        pad_h = (32 - h % 32) % 32
        pad_w = (32 - w % 32) % 32
        
        if pad_h > 0 or pad_w > 0:
            frame1 = torch.nn.functional.pad(frame1, (0, pad_w, 0, pad_h), mode="replicate")
            frame2 = torch.nn.functional.pad(frame2, (0, pad_w, 0, pad_h), mode="replicate")
        
        dt_tensor = frame1.new_full((1, 1), dt)
        result = self.model(frame1, frame2, dt_tensor)
        
        # Remove padding
        if pad_h > 0 or pad_w > 0:
            result = result[:, :, :h, :w]
        
        return result
    
    def plan_timing(
        self, num_frames: int, source_fps: float, target_fps: float
    ) -> List[tuple]:
        """
        Work out which frames to synthesise, as (index, dt) pairs.

        Output frame j sits at time j / target_fps. In source-frame coordinates
        that is pos = j * source_fps / target_fps, which lands between source
        frames floor(pos) and floor(pos) + 1 at fraction dt.

        The count is chosen so the last output lands exactly on the last input:
        floor((N-1) * ratio) + 1. That keeps first and last frames identical to
        the source and never extrapolates past the end, at the cost of the
        duration differing by up to one frame.

        Returns ideal positions. It is the caller's job to realise them — see
        interpolate_frames, which snaps them onto a recursively-built grid
        rather than asking the model for arbitrary dt, because this model does
        not honour dt (see that function's notes).
        """
        if num_frames < 2:
            raise ValueError(f"Need at least 2 frames, got {num_frames}")

        ratio = target_fps / source_fps
        count = int((num_frames - 1) * ratio) + 1
        step = source_fps / target_fps

        plan = []
        for j in range(count):
            pos = j * step
            i = int(pos)
            dt = pos - i
            if i >= num_frames - 1:             # clamp at the tail
                i, dt = num_frames - 2, 1.0
            if dt < 1e-6:
                plan.append((i, 0.0))           # verbatim source frame
            elif dt > 1.0 - 1e-6:
                plan.append((i + 1, 0.0))
            else:
                plan.append((i, dt))
        return plan

    @torch.no_grad()
    def interpolate_frames(
        self,
        frames: List[torch.Tensor],
        source_fps: float,
        target_fps: float,
        preserve_source_frames: bool = True,
        progress_callback: Optional[Callable] = None,
    ) -> List[torch.Tensor]:
        """
        Retime a list of frame tensors to a new frame rate. No disk, no codec.

        This is the real entry point — interpolate_video is a thin wrapper that
        adds decode and encode around it. Takes and returns float32 CPU tensors
        shaped [1, 3, H, W], so a caller holding decoded latents can retime them
        without a round trip through PNG and H.264.

        How the timing is realised, and why not with dt
            The model accepts a dt argument and responds to it monotonically, so
            synthesising each output frame at its exact time looks like the
            obvious approach. It does not work on this checkpoint. Measured
            against a real pair whose true |f0-f1| was 0.0057:

                dt 0.0 -> 1.0 across one pair spanned only 0.0015  (26%)
                dt 0.4 -> 0.8 spanned 0.0007, expected 0.0023      (30%)
                the same interval across a pair boundary: 0.0052

            The model returns a near-midpoint frame almost regardless of dt, so
            several samples from one pair come back nearly identical and all the
            motion collects at the pair boundaries. In a 24 -> 60 test that
            produced a hard period-5 stutter: inter-frame deltas alternating
            0.12 / 1.19 with lag-1 correlation -0.48.

            Recursive subdivision avoids this because every level builds new
            pairs with real endpoints, keeping the model in the midpoint regime
            it is actually trained for. So: subdivide onto a dense power-of-two
            grid, then take the grid frame nearest each ideal time.

            That leaves a bounded timing quantisation — half a grid step, and
            the grid is at least twice as dense as the target rate — instead of
            the old behaviour, which handed the surplus to ffmpeg's -r and let
            it drop frames on an uneven cadence.
        """
        self._ensure_model()

        ratio = target_fps / source_fps
        plan = self.plan_timing(len(frames), source_fps, target_fps)

        if ratio <= 1.0:
            # Downsampling or identity: pick nearest source frames, no synthesis.
            print(f"[FILM] {len(frames)} -> {len(plan)} frames "
                  f"({source_fps}fps -> {target_fps}fps, selection only)")
            return [frames[min(int(round(i + dt)), len(frames) - 1)].float()
                    for i, dt in plan]

        # Grid at least 2x denser than the target, capped at 8x, so the nearest
        # grid frame is never more than half a grid step from the ideal time.
        levels = max(1, min(3, math.ceil(math.log2(ratio)) + 1))
        grid = 2 ** levels

        print(f"[FILM] {len(frames)} -> {len(plan)} frames "
              f"({source_fps}fps -> {target_fps}fps, ratio {ratio:.3f}x)")
        print(f"[FILM] Subdividing {grid}x, then selecting nearest of "
              f"{(len(frames) - 1) * grid + 1} grid frames")

        dense = self.interpolate_recursive(
            [f.to(device=self.device, dtype=self.precision) for f in frames],
            levels, progress_callback,
        )
        dense = [d.float().cpu() for d in dense]

        out: List[torch.Tensor] = []
        max_err = 0.0
        for i, dt in plan:
            ideal = i + dt
            k = int(round(ideal * grid))
            k = max(0, min(k, len(dense) - 1))
            max_err = max(max_err, abs(k / grid - ideal))
            # Source frames survive the recursion untouched at multiples of the
            # grid, so preserving them is a matter of not overriding that.
            if preserve_source_frames and abs(ideal - round(ideal)) < 1e-6:
                out.append(frames[int(round(ideal))].float())
            else:
                out.append(dense[k])

        print(f"[FILM] Max timing error: {max_err:.4f} source intervals "
              f"({max_err / source_fps * 1000:.1f}ms)")
        del dense
        if torch.cuda.is_available():
            torch.cuda.empty_cache()
        return out

    def interpolate_recursive(
        self,
        frames: List[torch.Tensor],
        times_to_interpolate: int,
        progress_callback: Optional[Callable] = None,
    ) -> List[torch.Tensor]:
        """
        Recursively interpolate between frames — FILM's native mode.
        
        Each level doubles the frame count by inserting midpoints between
        every adjacent pair. This is higher quality than linear dt spacing
        because each interpolation is always at dt=0.5 (the sweet spot).
        
        Args:
            frames: List of [1, 3, H, W] tensors
            times_to_interpolate: Number of recursive passes
                1 = 2x frames, 2 = 4x frames, 3 = 8x frames
            progress_callback: Optional (progress, message) callback

        Returns:
            List of interpolated [1, 3, H, W] tensors

        Legacy — nothing in FUK calls this. Binary subdivision can only produce
        power-of-two multiples, so a 1.5x conversion had to overshoot to 2x and
        let ffmpeg discard the surplus. interpolate_frames synthesises each
        output frame at its exact time instead. Kept because it is public API
        and is still the right tool if you specifically want 2x/4x/8x.
        """
        self._ensure_model()
        
        result = list(frames)
        total_passes = times_to_interpolate
        
        for level in range(times_to_interpolate):
            new_result = [result[0]]
            pairs_total = len(result) - 1
            
            for i in range(pairs_total):
                mid = self.interpolate_pair(result[i], result[i + 1], dt=0.5)
                new_result.append(mid)
                new_result.append(result[i + 1])
                
                if progress_callback:
                    overall = (level + (i + 1) / pairs_total) / total_passes
                    progress_callback(
                        0.2 + 0.6 * overall,
                        f"FILM pass {level + 1}/{total_passes}, "
                        f"pair {i + 1}/{pairs_total}"
                    )
            
            result = new_result
            print(f"[FILM] Level {level + 1}/{total_passes}: {len(result)} frames")
        
        return result
    
    # ========================================================================
    # Video Pipeline
    # ========================================================================
    
    def extract_frames(
        self,
        video_path: Path,
        output_dir: Path,
        progress_callback: Optional[Callable] = None,
    ) -> List[Path]:
        """Extract frames from video using ffmpeg."""
        output_dir.mkdir(parents=True, exist_ok=True)
        
        if progress_callback:
            progress_callback(0.05, "Extracting frames from video")
        
        # Use PNG for lossless extraction
        frame_pattern = output_dir / "%08d.png"
        cmd = [
            "ffmpeg", "-y",
            "-i", str(video_path),
            "-fps_mode", "passthrough",
            "-start_number", "0",
            str(frame_pattern),
        ]
        
        print(f"[FILM] Extracting frames: {' '.join(cmd)}")
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        if result.returncode != 0:
            raise RuntimeError(f"Frame extraction failed: {result.stderr}")
        
        frames = sorted(output_dir.glob("*.png"))
        print(f"[FILM] Extracted {len(frames)} frames")
        return frames
    
    def frames_to_video(
        self,
        frames_dir: Path,
        output_path: Path,
        input_fps: float,
        output_fps: int = 24,
        progress_callback: Optional[Callable] = None,
    ) -> Path:
        """Encode frames back to video with ffmpeg."""
        if progress_callback:
            progress_callback(0.9, "Encoding output video")
        
        frame_files = sorted(frames_dir.glob("*.png"))
        num_frames = len(frame_files)
        
        if num_frames == 0:
            raise RuntimeError("No frames to encode")
        
        # Detect naming pattern
        first_name = frame_files[0].stem
        if first_name.startswith("frame_"):
            frame_pattern = frames_dir / "frame_%05d.png"
        else:
            num_digits = len(first_name)
            frame_pattern = frames_dir / f"%0{num_digits}d.png"
        
        expected_duration = num_frames / input_fps
        print(f"[FILM] Encoding {num_frames} frames")
        print(f"[FILM]   Input: {input_fps}fps, Output: {output_fps}fps")
        print(f"[FILM]   Expected duration: {expected_duration:.2f}s")
        
        cmd = [
            "ffmpeg", "-y",
            "-framerate", str(input_fps),
            "-i", str(frame_pattern),
            "-r", str(output_fps),
            "-c:v", "libx264",
            "-preset", "slow",
            "-crf", "14",
            "-pix_fmt", "yuv444p",
            str(output_path),
        ]
        
        result = subprocess.run(cmd, capture_output=True, text=True)
        
        if result.returncode != 0:
            raise RuntimeError(f"Video encoding failed: {result.stderr}")
        
        print(f"[FILM] Output: {output_path}")
        return output_path
    
    def get_video_info(self, video_path: Path) -> Dict[str, Any]:
        """Get video FPS, frame count, and duration via ffprobe."""
        cmd = [
            "ffprobe", "-v", "error",
            "-select_streams", "v:0",
            "-show_entries", "stream=nb_frames,r_frame_rate,duration",
            "-of", "json",
            str(video_path),
        ]
        
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            return {}
        
        try:
            data = json.loads(result.stdout)
            stream = data.get("streams", [{}])[0]
            
            fps_str = stream.get("r_frame_rate", "16/1")
            if "/" in fps_str:
                num, den = fps_str.split("/")
                fps = float(num) / float(den)
            else:
                fps = float(fps_str)
            
            nb_frames = stream.get("nb_frames")
            if nb_frames and nb_frames != "N/A":
                frame_count = int(nb_frames)
            else:
                duration = float(stream.get("duration", 0))
                frame_count = int(duration * fps)
            
            return {
                "fps": fps,
                "frame_count": frame_count,
                "duration": frame_count / fps if fps > 0 else 0,
            }
        except Exception:
            return {}
    
    def interpolate_video(
        self,
        input_path: Path,
        output_path: Path,
        source_fps: int = 16,
        target_fps: int = 24,
        model: str = "film",
        output_mode: str = "mp4",
        bit_depth: int = 8,
        sequence_dir: Optional[Path] = None,
        progress_callback: Optional[Callable] = None,
    ) -> Dict[str, Any]:
        """
        Decode a video, retime it, encode it back. A wrapper around
        interpolate_frames, which is where the actual work happens.

        output_mode
            "mp4"      encode a video (default, unchanged behaviour)
            "sequence" write a PNG sequence and no video
            "both"     both
        bit_depth
            8 or 16, for the PNG sequence. 16 is worth it for anything headed
            further down a pipeline; it is ignored for mp4.
        sequence_dir
            Where the sequence lands. Defaults to a directory beside
            output_path. Sequences used to be written into a TemporaryDirectory
            and deleted before the caller ever saw them, so the only way to get
            frames out was to re-extract them from the encoded video — an
            entirely avoidable lossy generation.

        Duration is preserved: more frames at the higher rate, same running time.
        """
        input_path = Path(input_path)
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        
        start_time = time.time()
        
        # Get source info
        video_info = self.get_video_info(input_path)
        detected_fps = video_info.get("fps", source_fps)
        actual_source_fps = detected_fps if detected_fps > 0 else source_fps
        source_duration = video_info.get("duration", 0)
        
        if output_mode not in ("mp4", "sequence", "both"):
            raise ValueError(f"output_mode must be mp4, sequence or both; got {output_mode!r}")

        fps_ratio = target_fps / actual_source_fps

        print(f"[FILM] ===== FRAME INTERPOLATION (FILM) =====")
        print(f"[FILM] Input: {input_path.name}")
        print(f"[FILM] Source: {actual_source_fps}fps, Duration: {source_duration:.2f}s")
        print(f"[FILM] Target: {target_fps}fps  (ratio {fps_ratio:.3f}x, exact timing)")
        print(f"[FILM] Output: {output_mode}"
              + (f", {bit_depth}-bit PNG" if output_mode != "mp4" else ""))

        if sequence_dir is None:
            sequence_dir = output_path.parent / f"{output_path.stem}_frames"
        sequence_dir = Path(sequence_dir)

        with tempfile.TemporaryDirectory() as temp_dir:
            input_frames_dir = Path(temp_dir) / "input_frames"

            # 1. Decode to lossless PNG, then to float32 CPU tensors
            frame_paths = self.extract_frames(input_path, input_frames_dir, progress_callback)
            num_source = len(frame_paths)
            if num_source < 2:
                raise ValueError(f"Need at least 2 frames, got {num_source}")

            if progress_callback:
                progress_callback(0.15, f"Loading {num_source} frames")
            tensors = [self._load_frame(p) for p in frame_paths]

            # 2. Retime — the whole job, in memory
            interpolated = self.interpolate_frames(
                tensors, actual_source_fps, target_fps, progress_callback
            )
            num_output = len(interpolated)

            del tensors
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

            # 3. Write whatever was asked for
            sequence_paths: List[Path] = []
            if output_mode in ("sequence", "both"):
                sequence_dir.mkdir(parents=True, exist_ok=True)
                if progress_callback:
                    progress_callback(0.85, f"Writing {num_output} frames")
                for idx, tensor in enumerate(interpolated):
                    p = sequence_dir / f"frame_{idx:05d}.png"
                    self._save_frame(tensor, p, bit_depth=bit_depth)
                    sequence_paths.append(p)
                print(f"[FILM] Wrote {num_output} {bit_depth}-bit frames to {sequence_dir}")

            if output_mode in ("mp4", "both"):
                # Encoding needs 8-bit frames on disk; reuse the sequence when
                # one was written at 8-bit, otherwise stage a temporary copy.
                if output_mode == "both" and bit_depth == 8:
                    encode_dir = sequence_dir
                else:
                    encode_dir = Path(temp_dir) / "encode_frames"
                    encode_dir.mkdir()
                    for idx, tensor in enumerate(interpolated):
                        self._save_frame(tensor, encode_dir / f"frame_{idx:05d}.png", bit_depth=8)

                # Frames are already at the target rate, so input and output fps
                # match and ffmpeg has nothing to drop. The old path fed frames
                # at source x 2^k and relied on -r to discard the surplus, which
                # is what made non-power-of-two conversions stutter.
                self.frames_to_video(
                    encode_dir, output_path,
                    input_fps=target_fps,
                    output_fps=target_fps,
                    progress_callback=progress_callback,
                )

            del interpolated

        elapsed = time.time() - start_time

        if progress_callback:
            progress_callback(1.0, "Complete")

        print(f"[FILM] Done in {elapsed:.1f}s")

        return {
            "output_path": str(output_path) if output_mode in ("mp4", "both") else str(sequence_dir),
            "video_path": str(output_path) if output_mode in ("mp4", "both") else None,
            "sequence_dir": str(sequence_dir) if output_mode in ("sequence", "both") else None,
            "sequence_frames": [str(p) for p in sequence_paths],
            "bit_depth": bit_depth if output_mode != "mp4" else 8,
            "source_fps": actual_source_fps,
            "target_fps": target_fps,
            "source_frames": num_source,
            "interpolated_frames": num_output,
            "multiplier": num_output / num_source if num_source else 0,
            "duration": source_duration,
            "elapsed_seconds": elapsed,
            "method": "film",
        }


# ============================================================================
# Module Test
# ============================================================================

if __name__ == "__main__":
    import argparse
    
    parser = argparse.ArgumentParser(description="FILM frame interpolation")
    parser.add_argument("input", help="Input video path")
    parser.add_argument("output", help="Output video path")
    parser.add_argument("--source-fps", type=int, default=16)
    parser.add_argument("--target-fps", type=int, default=24)
    parser.add_argument("--device", default=None)
    args = parser.parse_args()
    
    interp = FILMInterpolator(device=args.device)
    result = interp.interpolate_video(
        Path(args.input), Path(args.output),
        source_fps=args.source_fps,
        target_fps=args.target_fps,
    )
    
    print(f"\nResult: {json.dumps(result, indent=2)}")
    interp.cleanup()